name: Pushing to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
 build:
  runs-on: ubuntu-latest

  permissions:
    pages: write      # to deploy to Pages
    id-token: write   # to verify the deployment originates from an appropriate source
  
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v3
  - name: Deploy
    id: deployment
    uses: actions/deploy-pages@v4




